server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  rabbitmq:
    host: 192.168.200.132
    port: 5672
    username: admin
    password: admin
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2     # 设置心跳的时间间隔（默认是30s）
    lease-expiration-duration-in-seconds: 5  # 两次心跳的间隔时间（默认是90s）
    instance-id: receive-8802.com               # 在eureka信息页面显示主机的名称
    prefer-ip-address: true                  # 访问路径变为 IP 地址