server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心动态创建路由的功能，利用服务名进行路由
      routes:
        - id: payment_route             #路由的ID，没有固定规则但要求唯一
#          uri: http://localhost:8001    #匹配提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**      #断言，路径相匹配的进行路由

        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            - Cookie=nick, ni.k
eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway9527

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
